CREATE TABLE IF NOT EXISTS admin_invites (
    id SERIAL PRIMARY KEY,
    token UUID NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
